// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD9D2XWSg6Z1VH6SX_Kz55HWozrzFYfGQ',
    appId: '1:1010668070729:web:f23de106596acf9d0e5c98',
    messagingSenderId: '1010668070729',
    projectId: 'healio-help',
    authDomain: 'healio-help.firebaseapp.com',
    storageBucket: 'healio-help.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJtlvWBImqRmS2kXKjlxj6ixeNW9u5Ps4',
    appId: '1:1010668070729:android:b8db6cdddd1252660e5c98',
    messagingSenderId: '1010668070729',
    projectId: 'healio-help',
    storageBucket: 'healio-help.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbDIi1Ic-yEhSHk0fCNbz7_NClBY9qN9s',
    appId: '1:1010668070729:ios:e4b697dad3b58e740e5c98',
    messagingSenderId: '1010668070729',
    projectId: 'healio-help',
    storageBucket: 'healio-help.firebasestorage.app',
    iosBundleId: 'com.example.healio',
  );
}
